{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.auth.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.auth.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.auth.username }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.auth.password }}"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command: ["bash", "-c", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["bash", "-c", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.mysql.persistence.storageClassName }}
        storageClassName: "{{ .Values.mysql.persistence.storageClassName }}"
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
{{- end }}
